### ISSUE TITLE
onClosePressed() not defined and No sound

### ISSUE THREAD

**Issue by ibraizQazi** [cubbuk/react-native-video-player#1]
I'm fairly new to React Native so I was trying some stuff and found your post on Medium, so I gave it a try. After some configuration and tweaks in android files I was able to run it on both virtual and actual device (samsung S4 and another samsung) but I wasn't getting any sound and the close button is also not working. I'm also trying to fix the rotation issue but I would appreciate help as I'm new to both javascript and react native.
PS: It is the best player out there.

**Comment by cubbuk** [comment]
Hi @ibraizQazi 

by using onCloseButton you can set your state to remove this view from your render function, I updated the codebase reflect that example, otherwise `onClosePressed` doesn't do anything else.

For volume I also updated the codebase so that you can change the volume by passing props, just please check the latest commit.

For rotation and stuff you shall check the great library `react-native-video` which I used in this toy project to play the video, hope it will help you.

**Comment by ibraizQazi** [comment]
@cubbuk  thank you for your help,  I just omitted the onclose code as I was using the android back button. the volume was working fine as you fixed it. Aesthetics need some work and autohide kind of thing. Thanks again.

**Comment by cubbuk** [comment]
@ibraizQazi I would recommend you to take a look at the following repo https://github.com/react-native-community/react-native-video. It is the library I am using in this sample project.
